[package]
name = "io-uring-write-file"
version = "0.1.0"
authors = ["Îºeen <3han5chou7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
io-uring = "0.4.0"
libc = "0.2.85"
